import { StyleSheet, Dimensions, ViewStyle, TextStyle, ImageStyle } from "react-native";

const { width } = Dimensions.get("window");


const colors = {
    deepPurple: "#6B46C1", 
    mediumPurple: "#8E2DE2", 
    mediumLightPurple: "#9F7AEA", 
    lightPurple: "#B794F4", 
    buttonPurple: "#805AD5", 
    cardOpacityDeepPurple: "rgba(107, 70, 193, 0.6)", 
    cardOpacityMediumLightPurple: "rgba(159, 122, 234, 0.6)", 
    white: "#FFFFFF", 
    lightGray: "#F8F9FA", 
    mediumGray: "#E9ECEF", 
    darkGray: "#CED4DA", 
    textDark: "#212529", 
    textMedium: "#495057", 
    textLight: "#6C757D", 
    spotifyGreen: "#1DB954", 
    errorRed: "#DC3545", 
    warningYellow: "#FFD700", 
    primaryBlue: "#007BFF", 
};

const newLayoutStyles = StyleSheet.create<{ [key: string]: ViewStyle | TextStyle | ImageStyle }>({
    container: {
        flex: 1,
        backgroundColor: colors.lightGray, 
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: colors.lightGray, 
        padding: 20,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 16,
        color: colors.textMedium, 
        textAlign: "center",
    },
    inlineLoadingIndicator: {
        position: "absolute",
        top: 15,
        right: 15,
        zIndex: 10,
    },
    mainContentContainer: {
        flexDirection: "row",
        justifyContent: "center",
        paddingVertical: 30,
        paddingHorizontal: width > 1000 ? 50 : 25,
        gap: width > 1000 ? 40 : 25,
        alignItems: "flex-start",
        width: "100%",
        maxWidth: 1600,
        alignSelf: "center",
    },
    leftColumn: {
        flex: 1,
        flexDirection: "column",
        gap: 20,
    },
    rightColumn: {
        flex: 1,
        flexDirection: "column",
        top: 66, 
        gap: 20,
    },
    infoCard: {
        backgroundColor: colors.white, 
        borderRadius: 12,
        padding: width > 768 ? 25 : 20,
        shadowColor: "#000", 
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1, 
        shadowRadius: 8, 
        elevation: 5,
        borderWidth: 1,
        borderColor: colors.mediumGray, 
    },
    photoSectionCard: {
        backgroundColor: colors.white, 
        borderRadius: 12,
        padding: width > 768 ? 25 : 20,
        shadowColor: "#000", 
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1, 
        shadowRadius: 8, 
        elevation: 5,
        borderWidth: 1,
        borderColor: colors.mediumGray, 
        alignItems: "center",
    },
    spotifySectionCard: {
        backgroundColor: colors.white, 
        borderRadius: 12,
        paddingVertical: width > 768 ? 25 : 20,
        paddingHorizontal: 0, 
        shadowColor: "#000", 
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1, 
        shadowRadius: 8, 
        elevation: 5,
        borderWidth: 1,
        borderColor: colors.mediumGray, 
        overflow: "hidden", 
    },
    sectionTitle: {
        fontSize: width > 768 ? 22 : 20,
        fontWeight: "700", 
        marginBottom: 15,
        color: colors.textDark, 
        paddingHorizontal: 5, 
    },
    cardTitle: {
        fontSize: width > 768 ? 17 : 16,
        fontWeight: "600",
        color: colors.textMedium, 
        marginBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: colors.mediumGray, 
        paddingBottom: 10,
        width: "100%", 
    },
    profileName: {
        fontSize: width > 768 ? 28 : 26, 
        fontWeight: "bold",
        marginBottom: 18,
        color: colors.textDark, 
        textAlign: "left",
        width: "100%", 
    },
    detailRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
        width: "100%", 
    },
    detailIcon: {
        fontSize: 16,
        color: colors.deepPurple, 
        marginRight: 12,
        width: 22,
        textAlign: "center",
    },
    detailLabel: {
        fontSize: 14,
        color: colors.textMedium, 
        fontWeight: "500",
        marginRight: 8, 
        minWidth: 100, 
    },
    detailValue: {
        fontSize: 14,
        color: colors.textDark, 
        flexShrink: 1,
        lineHeight: 20,
    },
    aboutText: {
        fontSize: 14,
        color: colors.textMedium, 
        lineHeight: 21,
    },
    infoText: {
        fontSize: 14,
        color: colors.textLight, 
        textAlign: "center",
        marginTop: 15,
        marginBottom: 15,
        paddingHorizontal: 10,
    },
    photosGridContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "flex-start",
        gap: 10, 
        marginTop: 15,
        width: "100%",
    },
    photoBox: {
        width: "31%", 
        aspectRatio: 1,
        backgroundColor: colors.mediumGray, 
        borderRadius: 10,
        position: "relative",
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        borderWidth: 1, 
        borderColor: colors.mediumGray,
    },
    photoThumbnail: {
        width: "100%",
        height: "100%",
    },
    deletePhotoIcon: {
        position: "absolute",
        top: 5, 
        right: 5, 
        backgroundColor: "rgba(255, 255, 255, 0.85)",
        borderRadius: 15,
        padding: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 3,
    },
    addPhotoBox: {
        width: "31%",
        borderWidth: 2,
        borderColor: colors.darkGray, 
        borderStyle: "dashed",
        backgroundColor: colors.lightGray, 
    },
    addPhotoText: {
        marginTop: 5,
        fontSize: 13,
        color: colors.textLight, 
        fontWeight: "500",
    },
    previewContainer: {
        width: "100%",
        alignItems: "center",
        backgroundColor: colors.lightGray, 
        padding: 20,
        borderRadius: 10,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: colors.mediumGray, 
    },
    previewImage: {
        width: width > 768 ? 200 : 180, 
        height: width > 768 ? 200 : 180,
        borderRadius: 10,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: colors.darkGray, 
    },
    previewButtonsContainer: {
        flexDirection: "row",
        justifyContent: "center",
        gap: 15,
        width: "100%", 
        marginTop: 10,
    },
    subTitle: {
        fontSize: width > 768 ? 16 : 15,
        fontWeight: "600",
        marginTop: 15,
        marginBottom: 12,
        color: colors.textMedium, 
        paddingHorizontal: 20,
    },
    spotifyItemBox: {
        width: width > 768 ? 120 : 110,
        alignItems: "center",
        marginHorizontal: width > 768 ? 8 : 5,
        marginBottom: 10,
        backgroundColor: colors.white, 
        borderRadius: 8,
        padding: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    spotifyItemImage: {
        width: width > 768 ? 100 : 90,
        height: width > 768 ? 100 : 90,
        borderRadius: 8, 
        backgroundColor: colors.mediumGray,
        marginBottom: 6, 
    },
    spotifyItemName: {
        fontSize: 12, 
        color: colors.textDark, 
        textAlign: "center",
        fontWeight: "500",
    },
    spotifyConnectContainer: {
        alignItems: "center",
        paddingVertical: 30,
        paddingHorizontal: 20,
    },
    button: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        marginVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
        minWidth: 120,
        alignSelf: "stretch", 
    },
    buttonText: {
        color: colors.white, 
        fontSize: 14,
        fontWeight: "bold",
        textAlign: "center",
    },
    confirmUploadButton: {
        backgroundColor: colors.buttonPurple, 
        flexGrow: 1,
        marginHorizontal: 0, 
    },
    cancelUploadButton: {
        backgroundColor: colors.textLight, 
        flexGrow: 1,
        marginHorizontal: 0, 
    },
    spotifyButton: {
        backgroundColor: colors.spotifyGreen,
        marginTop: 15,
        alignSelf: "center",
        paddingHorizontal: 25,
    },
    restaurantButton: {
        backgroundColor: "#FF6B6B", 
        marginTop: 15,
    },
    editButton: {
        backgroundColor: colors.primaryBlue, 
        marginTop: 5,
    },
    errorText: {
        color: colors.errorRed, 
        marginTop: 10,
        marginBottom: 15,
        textAlign: "center",
        fontSize: 15,
        paddingHorizontal: 10,
    },
});

export default newLayoutStyles;
